Name:           ros-jade-navigation-stage
Version:        0.2.2
Release:        0%{?dist}
Summary:        ROS navigation_stage package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/navigation_stage
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-amcl
Requires:       ros-jade-fake-localization
Requires:       ros-jade-gmapping
Requires:       ros-jade-map-server
Requires:       ros-jade-move-base
Requires:       ros-jade-stage-ros
BuildRequires:  ros-jade-catkin

%description
This package holds example launch files for running the ROS navigation stack in
stage.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Fri Mar 18 2016 William Woodall <william@osrfoundation.org> - 0.2.2-0
- Autogenerated by Bloom

* Wed Mar 16 2016 William Woodall <william@osrfoundation.org> - 0.2.1-0
- Autogenerated by Bloom

